export { default as MainPage } from './MainPage'
export { default as NotFound } from './NotFound'
export { default as ProfilePage } from './ProfilePage'
export { default as BasePage } from './BasePage'
export { default as AddPosition } from './AddPosition'
