export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as LoginPage } from './LoginPage'
export { default as Main } from './Main'
export { default as NotFound } from './NotFound'
export { default as Profile } from './Profile'
export { default as RegisterPage } from './RegisterPage'